plugins {
	alias libs.plugins.moddevgradle.legacy
}

legacyForge {
	mcpVersion = libs.versions.minecraft.get()

	parchment {
		minecraftVersion = libs.versions.parchment.minecraft.get()
		mappingsVersion = libs.versions.parchment.mappings.get()
	}
}

dependencies {
	annotationProcessor variantOf(libs.mixin) { classifier 'processor' }
	annotationProcessor libs.mixinextras.common

	compileOnly libs.bundles.mixin
    compileOnly libs.jetbrains.annotations

	implementation libs.resourcefulconfig

	// compileOnly variantOf(libs.emi) { classifier 'api' }
}

mixin {
	add(sourceSets.main, "${mod_id}.refmap.json")

	config("${mod_id}.mixins.json")
}
